name: Main Repo Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repo-A
      - name: Checkout Repo-A
        uses: actions/checkout@v4

      # Step 2: Make script executable
      - name: Make script executable
        run: chmod +x space_script.sh

      # Step 3: Run your script
      - name: Run the script
        run: ./space_script.sh

      # Step 4: Set up SSH for triggering Repo-B and Repo-C
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 5: Trigger Repo-B
      - name: Trigger Repo-B
        run: |
          git clone git@github.com:your-org/Repo-B.git
          cd Repo-B
          git pull origin main
          echo "Triggered from Repo-A" >> trigger.log
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add trigger.log
          git commit -m "Triggered from Repo-A [skip ci]" || echo "No changes to commit"
          git push origin main

      # Step 6: Trigger Repo-C
      - name: Trigger Repo-C
        run: |
          git clone git@github.com:your-org/Repo-C.git
          cd Repo-C
          git pull origin main
          echo "Triggered from Repo-A" >> trigger.log
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add trigger.log
          git commit -m "Triggered from Repo-A [skip ci]" || echo "No changes to commit"
          git push origin main
